Category.transaction do
  Category.create!(category_id: 124, name: "unicycles")
  Category.create!(category_id: 125, name: "motorized bicycles (diy)")
  Category.create!(category_id: 127, name: "engine kit parts")
  Category.create!(category_id: 128, name: "electrical")
  Category.create!(category_id: 129, name: "fuel components")
  Category.create!(category_id: 131, name: "gaskets and seals")
  Category.create!(category_id: 132, name: "wheels & brakes")
  Category.create!(category_id: 133, name: "baskets, racks & bags")
  Category.create!(category_id: 134, name: "bicycle engine kits")
  Category.create!(category_id: 135, name: "performance")
  Category.create!(category_id: 136, name: "clearance")
  Category.create!(category_id: 137, name: "wholesale engine kits")
  Category.create!(category_id: 138, name: "helmets")
  Category.create!(category_id: 139, name: "seat & seat covers")
  Category.create!(category_id: 140, name: "cylinder head")
  Category.create!(category_id: 141, name: "tools & chemicals")
  Category.create!(category_id: 142, name: "handlebars & grips")
  Category.create!(category_id: 143, name: "lights, horns & bells")
  Category.create!(category_id: 144, name: "bike locks")
  Category.create!(category_id: 145, name: "kickstands")
  Category.create!(category_id: 147, name: "bicycle mirrors")
  Category.create!(category_id: 148, name: "fenders & forks")
  Category.create!(category_id: 149, name: "cranks & pedals")
  Category.create!(category_id: 150, name: "apparel")
  Category.create!(category_id: 151, name: " 4-stroke parts")
  Category.create!(category_id: 152, name: "gas engine kits")
  Category.create!(category_id: 153, name: "electric motor kits")
  Category.create!(category_id: 154, name: "accessories")
  Category.create!(category_id: 155, name: "freestyle bmx")
  Category.create!(category_id: 157, name: "kids bikes")
  Category.create!(category_id: 158, name: "road bikes")
  Category.create!(category_id: 160, name: "mens beach cruisers")
  Category.create!(category_id: 161, name: "full suspension")
  Category.create!(category_id: 162, name: "hard tail")
  Category.create!(category_id: 163, name: "crankcase")
  Category.create!(category_id: 164, name: "drivetrain")
  Category.create!(category_id: 165, name: "classic bikes")
  Category.create!(category_id: 166, name: "fixed-gear bikes")
  Category.create!(category_id: 167, name: "folding bikes")
  Category.create!(category_id: 168, name: "view all parts")
  Category.create!(category_id: 169, name: "tandem/triplet bikes")
  Category.create!(category_id: 170, name: "2-stroke clutch")
  Category.create!(category_id: 171, name: "exhaust")
  Category.create!(category_id: 172, name: "chopper bikes")
  Category.create!(category_id: 173, name: "womens beach cruisers")
  Category.create!(category_id: 174, name: "mini dirt bikes")
end
