Item.transaction do
  Item.create!(item_id: 1155, name: "26 greenline womens bc-704")
  Item.create!(item_id: 1156, name: "26 micargi super m600")
  Item.create!(item_id: 1157, name: "26 greenline womens bc-109")
  Item.create!(item_id: 1158, name: "26 greenline womens bc-105dl")
  Item.create!(item_id: 1159, name: "20 greenline womens bc-200")
  Item.create!(item_id: 1160, name: "26 greenline bc-110 mens big guy")
  Item.create!(item_id: 1161, name: "26 greenline mens bc-106")
  Item.create!(item_id: 1162, name: "micargi high security u lock")
  Item.create!(item_id: 1163, name: "greenline large mounting metal cruiser basket")
  Item.create!(item_id: 1164, name: "micargi key cable lock")
  Item.create!(item_id: 1165, name: "micargi combo cable lock")
  Item.create!(item_id: 1166, name: "26 micargi womens tahiti")
  Item.create!(item_id: 1167, name: "26 micargi super m3000")
  Item.create!(item_id: 1168, name: "26 micargi super m1000")
  Item.create!(item_id: 1169, name: "20 micargi super m200")
  Item.create!(item_id: 1170, name: "20 micargi prado chopper")
  Item.create!(item_id: 1171, name: "20 micargi super m100")
  Item.create!(item_id: 1172, name: "24 micargi prado deluxe chopper")
  Item.create!(item_id: 1173, name: "26 micargi super m90")
  Item.create!(item_id: 1174, name: "24 micargi super m80")
  Item.create!(item_id: 1175, name: "26 micargi puma gts chopper")
  Item.create!(item_id: 1176, name: "20 micargi explorer bmx")
  Item.create!(item_id: 1177, name: "26 micargi puma deluxe chopper")
  Item.create!(item_id: 1178, name: "20 micargi explorer v2.0 bmx")
  Item.create!(item_id: 1179, name: "20 micargi excel bmx")
  Item.create!(item_id: 1180, name: "26 micargi falcon chopper")
  Item.create!(item_id: 1181, name: "20 micargi viper bmx")
  Item.create!(item_id: 1182, name: "26 micargi falcon gt")
  Item.create!(item_id: 1183, name: "27 micargi rs888")
  Item.create!(item_id: 1184, name: "26 micargi falcon gts")
  Item.create!(item_id: 1185, name: "26 micargi mens tahiti")
  Item.create!(item_id: 1186, name: "26  micargi mustang gts")
  Item.create!(item_id: 1187, name: "26 micargi mens tahiti nx3")
  Item.create!(item_id: 1188, name: "26 micargi womens tahiti nx3")
  Item.create!(item_id: 1189, name: "20 micargi jaos")
  Item.create!(item_id: 1190, name: "20 micargi leopard")
  Item.create!(item_id: 1191, name: "24 micargi leopard deluxe")
  Item.create!(item_id: 1192, name: "26 micargi mens pantera")
  Item.create!(item_id: 1193, name: "26 micargi classic")
  Item.create!(item_id: 1194, name: "16 micargi boys kiddy")
  Item.create!(item_id: 1195, name: "16 micargi girls kiddy")
  Item.create!(item_id: 1196, name: "12 micargi boys kidco")
  Item.create!(item_id: 1197, name: "12 micargi girls kidco")
  Item.create!(item_id: 1198, name: "12 micargi boys mbr12y")
  Item.create!(item_id: 1199, name: "12 micargi girls mbr12y")
  Item.create!(item_id: 1200, name: "20 micargi boys dragon")
  Item.create!(item_id: 1201, name: "20 micargi girls dragon")
  Item.create!(item_id: 1202, name: "16 micargi tiger")
  Item.create!(item_id: 1203, name: "26 micargi island")
  Item.create!(item_id: 1204, name: "26 micargi sport")
  Item.create!(item_id: 1205, name: "26 micargi womens m60")
  Item.create!(item_id: 1206, name: "26 micargi ls2007")
  Item.create!(item_id: 1207, name: "26 micargi womens pantera gts")
  Item.create!(item_id: 1208, name: "26 micargi mens pantera 7sp")
  Item.create!(item_id: 1209, name: "26 micargi mens rover")
  Item.create!(item_id: 1210, name: "26 micargi womens rover")
  Item.create!(item_id: 1211, name: "26 micargi mens rover gx")
  Item.create!(item_id: 1212, name: "26 micargi womens rover gx")
  Item.create!(item_id: 1213, name: "26 micargi mens rover nx3")
  Item.create!(item_id: 1214, name: "26 micargi womens rover nx3")
  Item.create!(item_id: 1215, name: "26 micargi mens rover gt")
  Item.create!(item_id: 1216, name: "26 micargi mens huntington")
  Item.create!(item_id: 1217, name: "26 micargi womens bronco gts")
  Item.create!(item_id: 1218, name: "26 micargi mens pantera gts")
  Item.create!(item_id: 1219, name: "24 micargi mens pantera")
  Item.create!(item_id: 1220, name: "24 micargi womens pantera")
  Item.create!(item_id: 1221, name: "20 micargi mens jetta")
  Item.create!(item_id: 1222, name: "20 micargi womens jetta")
  Item.create!(item_id: 1223, name: "20 micargi mens hero")
  Item.create!(item_id: 1224, name: "20 micargi womens hero")
  Item.create!(item_id: 1225, name: "micargi childrens helmet")
  Item.create!(item_id: 1226, name: "micargi adult helmet")
  Item.create!(item_id: 1227, name: "green line small metal hanging cruiser basket")
  Item.create!(item_id: 1228, name: "green line large metal hanging beach cruiser basket")
  Item.create!(item_id: 1229, name: "20 micargi m2")
  Item.create!(item_id: 1230, name: "26 micargi mens m60")
  Item.create!(item_id: 1231, name: "26 micargi mens m50")
  Item.create!(item_id: 1232, name: "26 micargi womens m50")
  Item.create!(item_id: 1233, name: "24 micargi mens m40")
  Item.create!(item_id: 1234, name: "24 micargi womens m40")
  Item.create!(item_id: 1235, name: "20 micargi mens m30")
  Item.create!(item_id: 1236, name: "20 micargi mens m20")
  Item.create!(item_id: 1237, name: "20 micargi womens m20")
  Item.create!(item_id: 1238, name: "26 micargi womens pantera 7sp")
  Item.create!(item_id: 1239, name: "26 greenline womens kruiser 1 a p l")
  Item.create!(item_id: 1240, name: "26 greenline cb-2601a")
  Item.create!(item_id: 1241, name: "26 greenline womens bc-106l")
  Item.create!(item_id: 1242, name: "gas cap")
  Item.create!(item_id: 1243, name: "26 greenline bc-113")
  Item.create!(item_id: 1244, name: "26 greenline bc-704")
  Item.create!(item_id: 1245, name: "26 greenline bc-103")
  Item.create!(item_id: 1246, name: "26 greenline bc-118")
  Item.create!(item_id: 1247, name: "26 greenline bc-115")
  Item.create!(item_id: 1248, name: "26 greenline mens kruiser 3 a p m")
  Item.create!(item_id: 1249, name: "green light hand made rattan basket")
  Item.create!(item_id: 1250, name: "26 greenline 3-speed bc-305")
  Item.create!(item_id: 1251, name: "green line dark ratan beach cruiser basket")
  Item.create!(item_id: 1252, name: "headlight - front with battery indicator")
  Item.create!(item_id: 1253, name: "66/80cc flying horse silver angle fire bicycle engine kit - 2 stroke")
  Item.create!(item_id: 1254, name: "chrome 24 inch wheel unicycle")
  Item.create!(item_id: 1255, name: "red 20 inch wheel unicycle")
  Item.create!(item_id: 1256, name: "blue 18 inch wheel unicycle")
  Item.create!(item_id: 1257, name: "red 16 inch wheel unicycle")
  Item.create!(item_id: 1258, name: "yellow 16 inch wheel unicycle")
  Item.create!(item_id: 1259, name: "26 greenline aluminum 3 spd premium bc-306pm")
  Item.create!(item_id: 1260, name: "26 greenline mens bc-119")
  Item.create!(item_id: 1261, name: "26 greenline mens kruiser 1 a p m")
  Item.create!(item_id: 1262, name: "26 greenline 7 speed tandem")
  Item.create!(item_id: 1263, name: "26 greenline 7-speed mens bc-706m")
  Item.create!(item_id: 1264, name: "26 greenline 3 spd premium womens bc-306pl")
  Item.create!(item_id: 1265, name: "26 greenline foldable 7 speed tandem")
  Item.create!(item_id: 1266, name: "20 greenline  boys bc-2006")
  Item.create!(item_id: 1267, name: "26 greenline 7-speed shimano tourney rd-tx55 womens bc-706 p l")
  Item.create!(item_id: 1268, name: "20 greenline aluminum bmx-122a")
  Item.create!(item_id: 1269, name: "24 greenline mens bc-2406")
  Item.create!(item_id: 1270, name: "24 greenline girls bc-2406")
  Item.create!(item_id: 1271, name: "26 greenline mens bc-105m")
  Item.create!(item_id: 1272, name: "20 greenline girls bc-2006")
  Item.create!(item_id: 1273, name: "24 micargi rover womens")
  Item.create!(item_id: 1274, name: "20 micargi low rider f4")
  Item.create!(item_id: 1275, name: "26 micargi mens general")
  Item.create!(item_id: 1276, name: "24 micargi jaos 3.0")
  Item.create!(item_id: 1277, name: "26 micargi polo")
  Item.create!(item_id: 1278, name: "20 micargi prince")
  Item.create!(item_id: 1279, name: "24 micargi mens rover")
  Item.create!(item_id: 1280, name: "26 micargi mens stealth beach cruiser")
  Item.create!(item_id: 1281, name: "26 micargi 3 spd mustang nx3")
  Item.create!(item_id: 1282, name: "26 micargi mens 7 speed rover")
  Item.create!(item_id: 1283, name: "26 micargi womens rover 7 speed")
  Item.create!(item_id: 1284, name: "26 micargi touch mens")
  Item.create!(item_id: 1285, name: "26 womens touch 7 speed")
  Item.create!(item_id: 1286, name: "26 micargi touch womens")
  Item.create!(item_id: 1287, name: "26 micargi sx4")
  Item.create!(item_id: 1288, name: "grubee skyhawk black 48cc bicycle engine kit epa certified")
  Item.create!(item_id: 1289, name: "magneto loop set")
  Item.create!(item_id: 1290, name: "cdi electron ignition coil")
  Item.create!(item_id: 1291, name: "nt carburetor")
  Item.create!(item_id: 1292, name: "alloy clutch lever")
  Item.create!(item_id: 1293, name: "throttle grip handle set")
  Item.create!(item_id: 1294, name: "kill switch")
  Item.create!(item_id: 1295, name: "chain idler pulley")
  Item.create!(item_id: 1296, name: "fuel valve")
  Item.create!(item_id: 1297, name: "clutch cable")
  Item.create!(item_id: 1298, name: "throttle cable")
  Item.create!(item_id: 1299, name: "fuel filter")
  Item.create!(item_id: 1300, name: "universal mounting bracket")
  Item.create!(item_id: 1301, name: "2.5 l black gas tank")
  Item.create!(item_id: 1302, name: "gas cap")
  Item.create!(item_id: 1303, name: "spark plug")
  Item.create!(item_id: 1304, name: "spark plug removal tool")
  Item.create!(item_id: 1305, name: "44 tooth sprocket")
  Item.create!(item_id: 1306, name: "sprocket clamp assembly")
  Item.create!(item_id: 1307, name: "415 heavy duty chain")
  Item.create!(item_id: 1308, name: "chain guard (black)")
  Item.create!(item_id: 1309, name: "epa certified chrome muffler")
  Item.create!(item_id: 1310, name: "epa certified black muffler")
  Item.create!(item_id: 1311, name: "muffler clamp")
  Item.create!(item_id: 1312, name: "66/80cc piston #2")
  Item.create!(item_id: 1313, name: "66cc (80cc) piston ring set")
  Item.create!(item_id: 1314, name: "415 chain master link")
  Item.create!(item_id: 1315, name: "vitta fuel line")
  Item.create!(item_id: 1316, name: "80cc cylinder body")
  Item.create!(item_id: 1317, name: "80cc cylinder body cap")
  Item.create!(item_id: 1318, name: "head stud cap nut set (4)")
  Item.create!(item_id: 1319, name: "motor mount")
  Item.create!(item_id: 1320, name: "motor mount bracket")
  Item.create!(item_id: 1321, name: "crank")
  Item.create!(item_id: 1322, name: "crank case gasket")
  Item.create!(item_id: 1323, name: "gear case gasket")
  Item.create!(item_id: 1324, name: "bottom head gasket")
  Item.create!(item_id: 1325, name: "66/80cc head gasket (top)")
  Item.create!(item_id: 1326, name: "muffler gasket")
  Item.create!(item_id: 1327, name: "magneto magnet")
  Item.create!(item_id: 1328, name: "202 main bearing")
  Item.create!(item_id: 1329, name: "small bevel wheel")
  Item.create!(item_id: 1330, name: "10 tooth drive sprocket")
  Item.create!(item_id: 1331, name: "drive sprocket removal tool")
  Item.create!(item_id: 1332, name: "clutch wheel nut")
  Item.create!(item_id: 1333, name: "small seal loop #2")
  Item.create!(item_id: 1334, name: "large seal loop")
  Item.create!(item_id: 1335, name: "intake / exhaust stud")
  Item.create!(item_id: 1336, name: "front motor mount stud")
  Item.create!(item_id: 1337, name: "motor head stud")
  Item.create!(item_id: 1338, name: "clutch shaft")
  Item.create!(item_id: 1339, name: "clutch pin mandrel")
  Item.create!(item_id: 1340, name: "clutch camshaft")
  Item.create!(item_id: 1341, name: "clutch arm")
  Item.create!(item_id: 1342, name: "clutch wire clip")
  Item.create!(item_id: 1343, name: "clutch bevel wheel")
  Item.create!(item_id: 1344, name: "crank cover")
  Item.create!(item_id: 1345, name: "gear case cover")
  Item.create!(item_id: 1346, name: "magneto case cover")
  Item.create!(item_id: 1347, name: "drive sprocket case cover")
  Item.create!(item_id: 1348, name: "26 greenline womens kruiser 3 a p l")
  Item.create!(item_id: 1349, name: "26 greenline womens kruiser 7 a l")
  Item.create!(item_id: 1350, name: "26 greenline mens kruiser 7 a p m")
  Item.create!(item_id: 1351, name: "greenline 7-speed tandem bct-709i")
  Item.create!(item_id: 1352, name: "bulk order-5 x flying horse silver 80cc bicycle engine kits epa")
  Item.create!(item_id: 1353, name: "bulk order-5 x flying horse black 80cc bicycle engine kits epa")
  Item.create!(item_id: 1356, name: "bulk order-10 flying horse x silver 80cc bicycle engine kits epa")
  Item.create!(item_id: 1357, name: "bulk order-10 x flying horse black 80cc bicycle engine kits epa")
  Item.create!(item_id: 1360, name: "motorized 26 micargi mens rover gx beach cruiser (diy)")
  Item.create!(item_id: 1361, name: "80cc angle fire cylinder body cap")
  Item.create!(item_id: 1362, name: "float kits")
  Item.create!(item_id: 1363, name: "combo brake and clutch lever")
  Item.create!(item_id: 1364, name: "1.5 l black gas tank")
  Item.create!(item_id: 1365, name: "1.5 l chrome gas tank")
  Item.create!(item_id: 1366, name: "2.5 l chrome gas tank")
  Item.create!(item_id: 1367, name: "36 tooth rear sprocket")
  Item.create!(item_id: 1368, name: "50 tooth sprocket")
  Item.create!(item_id: 1369, name: "standard  66/80cc bicycle engine only")
  Item.create!(item_id: 1370, name: "24 micargi royal")
  Item.create!(item_id: 1371, name: "clutch arm spring")
  Item.create!(item_id: 1372, name: "extension spring")
  Item.create!(item_id: 1373, name: "magneto case gasket")
  Item.create!(item_id: 1374, name: "motor mount stud")
  Item.create!(item_id: 1375, name: "universal t bracket")
  Item.create!(item_id: 1376, name: "grubee skyhawk silver 66/80cc angle fire bike engine kit epa cer")
  Item.create!(item_id: 1377, name: "metal wire rear rack")
  Item.create!(item_id: 1378, name: "66/80cc flying horse black angle fire bicycle engine kits - 2 stroke")
  Item.create!(item_id: 1379, name: "26 micargi womens rover lx")
  Item.create!(item_id: 1380, name: "26 micargi mens rover lx")
  Item.create!(item_id: 1381, name: "26 micargi mens touch 7 speed")
  Item.create!(item_id: 1382, name: "green line oval beach cruiser basket")
  Item.create!(item_id: 1383, name: "26 micargi womens cheetah gts")
  Item.create!(item_id: 1384, name: "26 micargi mens cheetah gts")
  Item.create!(item_id: 1385, name: "wellgo pedals")
  Item.create!(item_id: 1386, name: "greenline pedals")
  Item.create!(item_id: 1387, name: "greenline pedals with metal sides")
  Item.create!(item_id: 1388, name: "greenline round electric horn with mountings")
  Item.create!(item_id: 1389, name: "greenline kickstand")
  Item.create!(item_id: 1390, name: "greenline cushion grips with marine crops design")
  Item.create!(item_id: 1391, name: "greenline cushion grips with navy design")
  Item.create!(item_id: 1392, name: "greenline portable bicycle foot pump")
  Item.create!(item_id: 1393, name: "greenline bicycle seat")
  Item.create!(item_id: 1394, name: "greenline bicycle lock")
  Item.create!(item_id: 1395, name: "greenline helmet in black and pink")
  Item.create!(item_id: 1396, name: "greenline helmet in red")
  Item.create!(item_id: 1397, name: "greenline helmet in purple")
  Item.create!(item_id: 1398, name: "greenline helmet in pink")
  Item.create!(item_id: 1399, name: "greenline helmet in orange")
  Item.create!(item_id: 1400, name: "greenline helmet in mint green")
  Item.create!(item_id: 1401, name: "greenline helmet in flat black")
  Item.create!(item_id: 1402, name: "greenline helmet in graphite")
  Item.create!(item_id: 1403, name: "orange 16 inch wheel unicycle")
  Item.create!(item_id: 1404, name: "blue 16 inch wheel unicycle")
  Item.create!(item_id: 1405, name: "red 18 inch wheel unicycle")
  Item.create!(item_id: 1406, name: "yellow 18 inch wheel unicycle")
  Item.create!(item_id: 1407, name: "chrome 18 inch wheel unicycle")
  Item.create!(item_id: 1408, name: "chrome 20 inch wheel unicycle")
  Item.create!(item_id: 1409, name: "red 24 inch wheel unicycle")
  Item.create!(item_id: 1410, name: "chrome 16 inch wheel unicycle")
  Item.create!(item_id: 1411, name: "lemon 16 inch wheel unicycle")
  Item.create!(item_id: 1412, name: "lemon 18 inch wheel unicycle")
  Item.create!(item_id: 1413, name: "orange 18 inch wheel unicycle")
  Item.create!(item_id: 1414, name: "lemon 20 inch wheel unicycle")
  Item.create!(item_id: 1415, name: "20 micargi tt61a nx3")
  Item.create!(item_id: 1416, name: "20 micargi ta01b")
  Item.create!(item_id: 1417, name: "20 micargi ta07b 7sp")
  Item.create!(item_id: 1418, name: "heat shield spring")
  Item.create!(item_id: 1419, name: "intake manifold gasket")
  Item.create!(item_id: 1420, name: "spring gasket")
  Item.create!(item_id: 1421, name: "spring gasket pi-14")
  Item.create!(item_id: 1422, name: "piston pin #2")
  Item.create!(item_id: 1423, name: "chain guard (chrome)")
  Item.create!(item_id: 1424, name: "26 micargi womens pantera")
  Item.create!(item_id: 1426, name: "greenline womens helmet")
  Item.create!(item_id: 1427, name: "grubee skyhawk black 66/80cc angle fire bike engine kit epa cert")
  Item.create!(item_id: 1428, name: "grubee skyhawk silver 48cc bicycle engine angle fire kit epa cer")
  Item.create!(item_id: 1429, name: "26 mens micargi tahiti lx")
  Item.create!(item_id: 1430, name: "26 womens tahiti lx")
  Item.create!(item_id: 1431, name: "green line oval beach cruiser basket with top")
  Item.create!(item_id: 1432, name: "sunlite flame 26 x 3 tire")
  Item.create!(item_id: 1433, name: "synthetic leather cushion grips with stitching")
  Item.create!(item_id: 1434, name: "chrome 4 stroke muffler")
  Item.create!(item_id: 1435, name: "26 pink front rim")
  Item.create!(item_id: 1436, name: "26 micargi  womens cheetah")
  Item.create!(item_id: 1437, name: "26 micargi womens cheetah 7spd beach cruiser")
  Item.create!(item_id: 1438, name: "26 mens micargi cheetah nx3")
  Item.create!(item_id: 1439, name: "26 womens osaka")
  Item.create!(item_id: 1440, name: "26 mens micargi osaka")
  Item.create!(item_id: 1441, name: "26 micargi rd-268")
  Item.create!(item_id: 1442, name: "standard 26 inner tube")
  Item.create!(item_id: 1443, name: "bicycle tire levers 3 pack")
  Item.create!(item_id: 1444, name: "single boost bottle induction kit")
  Item.create!(item_id: 1445, name: "motorized 28 micargi mens osaka commuter bicycle (diy)")
  Item.create!(item_id: 1446, name: "dual boost bottle induction kit")
  Item.create!(item_id: 1447, name: "greenline classic 28 bike")
  Item.create!(item_id: 1448, name: "700c greenline xg-7000 fixie fixed gear racing bicycle")
  Item.create!(item_id: 1449, name: "26 micargi womens cheetah nx3")
  Item.create!(item_id: 1450, name: "micargi 48cm rd-267 fixed gear")
  Item.create!(item_id: 1451, name: "micargi 48cm rd-269 fixed gear")
  Item.create!(item_id: 1452, name: "26 micargi mens cheetah")
  Item.create!(item_id: 1453, name: "metal pedals")
  Item.create!(item_id: 1454, name: "bullet head light")
  Item.create!(item_id: 1455, name: "rectangle chrome mirror")
  Item.create!(item_id: 1456, name: "4 stroke pull start grubee skyhawk 49cc bicycle engine kits epa")
  Item.create!(item_id: 1457, name: "piston retaining clips")
  Item.create!(item_id: 1458, name: "clutch actuator bearing")
  Item.create!(item_id: 1459, name: "crank connector bearing")
  Item.create!(item_id: 1460, name: "clutch cover")
  Item.create!(item_id: 1461, name: "intake manifold")
  Item.create!(item_id: 1462, name: "accelerator grip retainer")
  Item.create!(item_id: 1463, name: "bucking bar")
  Item.create!(item_id: 1464, name: "shaft fixed pin")
  Item.create!(item_id: 1465, name: "pull start assembly")
  Item.create!(item_id: 1466, name: "26 greenline womens bc-105l")
  Item.create!(item_id: 1467, name: "26 greenline womens bc-106pl")
  Item.create!(item_id: 1468, name: "26 greenline mens bc-106pm")
  Item.create!(item_id: 1469, name: "micargi womens classic")
  Item.create!(item_id: 1470, name: "micargi mens classic")
  Item.create!(item_id: 1471, name: "26 micargi sx3")
  Item.create!(item_id: 1472, name: "greenline basket liner- small - dalmatian prints")
  Item.create!(item_id: 1473, name: "greenline basket liner- small - dog prints")
  Item.create!(item_id: 1474, name: "greenline basket liner- small - giraffe prints")
  Item.create!(item_id: 1475, name: "greenline basket liner- small - tiger prints")
  Item.create!(item_id: 1476, name: "greenline basket liner- small - leopard prints")
  Item.create!(item_id: 1477, name: "greenline basket liner- small - baby leopard prints")
  Item.create!(item_id: 1478, name: "greenline basket liner- small -zebra prints")
  Item.create!(item_id: 1479, name: "greenline basket liner- large- dog print")
  Item.create!(item_id: 1480, name: "greenline basket liner- large- giraffe print")
  Item.create!(item_id: 1481, name: "greenline basket liner- small- hibiscus prints")
  Item.create!(item_id: 1482, name: "greenline basket liner- large- baby leopard print")
  Item.create!(item_id: 1483, name: "greenline basket liner- large- dalmatian print")
  Item.create!(item_id: 1484, name: "greenline basket liner- large- tiger print")
  Item.create!(item_id: 1485, name: "greenline basket liner- large- leopard print")
  Item.create!(item_id: 1486, name: "greenline basket liner- large- zebra print")
  Item.create!(item_id: 1487, name: "greenline basket liner- large- hawaiian print")
  Item.create!(item_id: 1488, name: "greenline basket liner- large- hibiscus print")
  Item.create!(item_id: 1489, name: "greenline basket liner- large- turtle print")
  Item.create!(item_id: 1490, name: "greenline basket liner- small- turtle print")
  Item.create!(item_id: 1491, name: "greenline seat cover- dalmatian print")
  Item.create!(item_id: 1492, name: "greenline seat cover- tiger print")
  Item.create!(item_id: 1493, name: "greenline seat cover- leopard print")
  Item.create!(item_id: 1494, name: "greenline seat cover- giraffe print")
  Item.create!(item_id: 1495, name: "greenline seat cover- dog print")
  Item.create!(item_id: 1496, name: "greenline saddle with back rest")
  Item.create!(item_id: 1497, name: "greenline seat cover- baby leopard print")
  Item.create!(item_id: 1498, name: "greenline seat cover- hibiscus print")
  Item.create!(item_id: 1499, name: "greenline seat cover- hawaiian print")
  Item.create!(item_id: 1500, name: "greenline seat cover- turtle print")
  Item.create!(item_id: 1501, name: "greenline bell- small")
  Item.create!(item_id: 1502, name: "greenline bell- large")
  Item.create!(item_id: 1503, name: "greenline seat- extra soft - vanilla with black checker")
  Item.create!(item_id: 1504, name: "16 greenline- fb 1602")
  Item.create!(item_id: 1506, name: "flat key")
  Item.create!(item_id: 1507, name: "round chrome side mirror")
  Item.create!(item_id: 1508, name: "woodruff key")
  Item.create!(item_id: 1509, name: "greenline- axle pegs")
  Item.create!(item_id: 1510, name: "greenline- duck tail fenders")
  Item.create!(item_id: 1511, name: "26 x 1.75 silver front wheel with 36 spokes")
  Item.create!(item_id: 1512, name: "26 x 1.75 black front wheel with 36 spokes")
  Item.create!(item_id: 1513, name: "greenline- 36 spokes aluminum alloy wheel- front")
  Item.create!(item_id: 1514, name: "greenline- 36 spokes aluminum alloy wheel- front")
  Item.create!(item_id: 1515, name: "greenline- 36 spokes aluminum alloy wheel- rear")
  Item.create!(item_id: 1516, name: "greenline- 36 spokes aluminum alloy wheel- rear")
  Item.create!(item_id: 1517, name: "greenline- 36 spokes aluminum alloy wheel- rear")
  Item.create!(item_id: 1518, name: "motorized 26  greenline mens bc-106pm beach cruiser (diy)")
  Item.create!(item_id: 1519, name: "26 brake kit")
  Item.create!(item_id: 1520, name: "chain breaker")
  Item.create!(item_id: 1521, name: "wide crank assembly")
  Item.create!(item_id: 1522, name: "rear wheel adjustable kickstand")
  Item.create!(item_id: 1523, name: "bicycle tire repair kit")
  Item.create!(item_id: 1524, name: "heavy duty 26 inner tube")
  Item.create!(item_id: 1525, name: "standard alloy metal pedals 1/2 thread")
  Item.create!(item_id: 1526, name: "micargi bicycle lock")
  Item.create!(item_id: 1527, name: "chain idler pulley with bearing wheel")
  Item.create!(item_id: 1528, name: "chain idler pulley without bearing")
  Item.create!(item_id: 1529, name: "pulley wheel with bearing")
  Item.create!(item_id: 1530, name: "pulley wheel")
  Item.create!(item_id: 1531, name: "nitrous oxide kit")
  Item.create!(item_id: 1532, name: "66/80cc mega motors silver bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1533, name: "66/80cc mega motors black  bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1534, name: "cone cns high performance carburetor")
  Item.create!(item_id: 1535, name: "cns high performance carburetor")
  Item.create!(item_id: 1536, name: "bikeberry.com t-shirt")
  Item.create!(item_id: 1538, name: "26 greenline bc-106pl 2-tone")
  Item.create!(item_id: 1539, name: "motorized 26  greenline mens bc-706 beach cruiser (diy)")
  Item.create!(item_id: 1540, name: "maxima:  quick 2 mix bottle")
  Item.create!(item_id: 1541, name: "maxima scooter pro 2-stroke synthetic motor oil 1 liter")
  Item.create!(item_id: 1542, name: "maxima chain wax")
  Item.create!(item_id: 1543, name: "maxima clean up chain cleaner")
  Item.create!(item_id: 1544, name: "thh t-380 open face helmet")
  Item.create!(item_id: 1545, name: "2-stroke bicycle engine kit installation dvd")
  Item.create!(item_id: 1546, name: "48cc mega motors silver bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1547, name: "expansion chamber")
  Item.create!(item_id: 1548, name: "24 micargi womens tivola")
  Item.create!(item_id: 1549, name: "grubee skyhawk gt-5sr super rat silver 66/80cc angle fire bike e")
  Item.create!(item_id: 1550, name: "greenline- heavy duty springer fork")
  Item.create!(item_id: 1551, name: "main clutch spring")
  Item.create!(item_id: 1552, name: "round column bolt")
  Item.create!(item_id: 1553, name: "26 bronco 3.0 gts")
  Item.create!(item_id: 1554, name: "clutch screw base")
  Item.create!(item_id: 1555, name: "integrated brake lever and kill switch throttle handle assembly")
  Item.create!(item_id: 1556, name: "cns carburetor rebuild kit")
  Item.create!(item_id: 1557, name: "28 beach cruiser handlebar")
  Item.create!(item_id: 1558, name: "mini ape hanger handlebar")
  Item.create!(item_id: 1559, name: "27 stainless steel beach cruiser handlebar")
  Item.create!(item_id: 1560, name: "ape hanger handlebar")
  Item.create!(item_id: 1561, name: "forza 700x18-23 bicycle tube")
  Item.create!(item_id: 1562, name: "sunlite hl-l530 led headlight")
  Item.create!(item_id: 1563, name: "center kick stand")
  Item.create!(item_id: 1564, name: "rear axle kickstands")
  Item.create!(item_id: 1565, name: "bikemaster chain breaker")
  Item.create!(item_id: 1566, name: "park tool heavy duty steel tire lever set")
  Item.create!(item_id: 1567, name: "sunlite steel tire lever set")
  Item.create!(item_id: 1568, name: "sunlite 8-slot round spoke wrench")
  Item.create!(item_id: 1569, name: "sunlite freewheel remover")
  Item.create!(item_id: 1570, name: "sunlite hex head y wrench")
  Item.create!(item_id: 1571, name: "sunlite 30-32/36-40 head set")
  Item.create!(item_id: 1572, name: "sunlite series ii crank puller")
  Item.create!(item_id: 1573, name: "origin 8 chain tension adjuster")
  Item.create!(item_id: 1574, name: "sunlite bugle horn")
  Item.create!(item_id: 1575, name: "sunlite c-sport whipper snapper seat bag")
  Item.create!(item_id: 1576, name: "sunlite utili-t handlebar roll bag")
  Item.create!(item_id: 1577, name: "sunlite single speed 22 tooth sprocket")
  Item.create!(item_id: 1578, name: "spark plug cap")
  Item.create!(item_id: 1579, name: "sunlite grabber platform pedals")
  Item.create!(item_id: 1580, name: "sunlite alloy dual brake lever")
  Item.create!(item_id: 1581, name: "free wheel heavy duty axle kit")
  Item.create!(item_id: 1582, name: "26 micargi puma 3.0 gts stretch chopper")
  Item.create!(item_id: 1583, name: "26 micargi onyx mens beach cruiser")
  Item.create!(item_id: 1584, name: "26 micargi puma 3.0 stretch chopper")
  Item.create!(item_id: 1585, name: "26 micargi mens cougar gts beach cruiser")
  Item.create!(item_id: 1586, name: "chrome drive sprocket case cover")
  Item.create!(item_id: 1587, name: "chrome gear case cover")
  Item.create!(item_id: 1588, name: "chrome magneto case cover")
  Item.create!(item_id: 1589, name: "chrome case cover 3 pack")
  Item.create!(item_id: 1590, name: "48cc magneto case cover")
  Item.create!(item_id: 1591, name: "410 chain master link")
  Item.create!(item_id: 1592, name: "red baron aviator goggles")
  Item.create!(item_id: 1593, name: "cateye velo 5 bicycle computer")
  Item.create!(item_id: 1594, name: "48cc flying horse silver bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1595, name: "26 greenline womens bc-706pl")
  Item.create!(item_id: 1596, name: "49cc flying horse 5g pull start bicycle engine kit- 4 stroke")
  Item.create!(item_id: 1597, name: "410 bicycle engine chain")
  Item.create!(item_id: 1598, name: "66cc/80cc bottom crank case body")
  Item.create!(item_id: 1599, name: "1 x 15 layback seat post")
  Item.create!(item_id: 1600, name: "1 x 12 chrome seat post")
  Item.create!(item_id: 1601, name: "sprocket clamp assembly nuts (9 pack)")
  Item.create!(item_id: 1602, name: "park tool pcs-9 home mechanic repair stand")
  Item.create!(item_id: 1603, name: "drive sprocket case cover screws")
  Item.create!(item_id: 1604, name: "high performance three-prong spark plug")
  Item.create!(item_id: 1605, name: "sunlite tl-l520 led taillight")
  Item.create!(item_id: 1606, name: "sunlite tl-l510 led taillight")
  Item.create!(item_id: 1607, name: "jnm vibration motor mounts")
  Item.create!(item_id: 1608, name: "small seal loop #1")
  Item.create!(item_id: 1609, name: "66/80cc piston #5")
  Item.create!(item_id: 1610, name: "piston pin #5")
  Item.create!(item_id: 1611, name: "liquid caddy beverage holder")
  Item.create!(item_id: 1612, name: "sunlite 26 mtb front and rear brake kit")
  Item.create!(item_id: 1613, name: "rbr vintage victor/hairpin style saddle")
  Item.create!(item_id: 1614, name: "jnm sound dampener kit")
  Item.create!(item_id: 1615, name: "motorized 26 micargi mens stealth beach cruiser (diy)")
  Item.create!(item_id: 1616, name: "motorized 26 micargi mens tahiti beach cruiser (diy)")
  Item.create!(item_id: 1617, name: "motorized 26 micargi mens pantera beach cruiser (diy)")
  Item.create!(item_id: 1618, name: "motorized 26 micargi mens pantera gts beach cruiser (diy)")
  Item.create!(item_id: 1619, name: "motorized 26 micargi mens general beach cruiser (diy)")
  Item.create!(item_id: 1620, name: "motorized 26 micargi mens huntington beach cruiser bike (diy)")
  Item.create!(item_id: 1621, name: "motorized 26 micargi mens m50 mountain bike (diy)")
  Item.create!(item_id: 1622, name: "48cc flying horse pull start centrifugal clutch bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1623, name: "48cc flying horse black bicycle engine kit- 2 stroke")
  Item.create!(item_id: 1624, name: "26 greenline mens bc-105dm")
  Item.create!(item_id: 1625, name: "26 greenline mens kruiser 7 a p m")
  Item.create!(item_id: 1626, name: "26 greenline mens kruiser 1 a m")
  Item.create!(item_id: 1627, name: "26 greenline mens kruiser 3 a p m")
  Item.create!(item_id: 1628, name: "bullet head light generator kit")
  Item.create!(item_id: 1629, name: "pyramid bicycle brake cable")
  Item.create!(item_id: 1630, name: "sunlite rear extension fender")
  Item.create!(item_id: 1631, name: "sunlite 26 v brake fork")
  Item.create!(item_id: 1632, name: "trik topz custom valve cap")
  Item.create!(item_id: 1633, name: "rbr small vintage saddle")
  Item.create!(item_id: 1634, name: "greenline seat- oversize")
  Item.create!(item_id: 1635, name: "sunlite cloud-9 gel cruiser saddle")
end
